version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - C:/Users/djbla/OneDrive/Documents/dev/fullStackOpen parent-dir/part12/part12-containers-applications/todo-app/todo-backend/mongo/mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
volumes:
  mongo_data:
